% addpath('./kinematics', './control', './dynamics', './set_parameters/', ...
%     './solve_eqns/', './visualize', './analysis')

addpath('./Legged Robots/Assignment 4/assign4/kinematics', './Legged Robots/Assignment 4/assign4/control', './Legged Robots/Assignment 4/assign4/dynamics', './Legged Robots/Assignment 4/assign4/set_parameters/', ...
    './Legged Robots/Assignment 4/assign4/solve_eqns/', './Legged Robots/Assignment 4/assign4/visualize', './Legged Robots/Assignment 4/assign4/analysis')
