function A_m = Am_tmp(l1,l2,l3,m,m3,q1_m,q2_m,q3_m)
%AM_TMP
%    A_M = AM_TMP(L1,L2,L3,M,M3,Q1_M,Q2_M,Q3_M)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Nov-2018 16:10:28

t2 = l1.^2;
A_m = [m.*t2.*(-5.0./4.0)-m3.*t2+l1.*l2.*m.*cos(q1_m-q2_m).*(1.0./2.0)-l1.*l3.*m3.*cos(q1_m-q3_m).*(1.0./2.0),0.0,l3.^2.*m3.*(-1.0./4.0)];
