function A_m = Am_tmp(l1,l2,l3,m,m3,q1_m,q2_m,q3_m)
%AM_TMP
%    A_M = AM_TMP(L1,L2,L3,M,M3,Q1_M,Q2_M,Q3_M)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Oct-2018 14:06:42

t2 = cos(q1_m);
t3 = abs(l1.*t2.*(1.0./2.0)-l2.*cos(q2_m));
t4 = abs(l1.*sin(q1_m).*(1.0./2.0)-l2.*sin(q2_m));
A_m = [l1.*m.*t2.*sqrt(t3.^2+t4.^2).*(-1.0./2.0),0.0,l3.^2.*m3.*cos(q3_m).*(1.0./4.0)];
