function A_p = Ap_tmp(l1,l2,l3,m,m3,q1_p,q2_p,q3_p)
%AP_TMP
%    A_P = AP_TMP(L1,L2,L3,M,M3,Q1_P,Q2_P,Q3_P)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    04-Nov-2018 16:10:28

t2 = l1.^2;
A_p = [m.*t2.*(-5.0./4.0)-m3.*t2+l1.*l2.*m.*cos(q1_p-q2_p).*(1.0./2.0)-l1.*l3.*m3.*cos(q1_p-q3_p).*(1.0./2.0),l2.^2.*m.*(-1.0./4.0),l2.*l3.*m3.*cos(q2_p-q3_p).*(1.0./4.0)];
